# Application
spring.application.name=URLShortner
server.port=${PORT:8080}

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d6rcijhaae7s739u1j80-a:5432/urlshortner_wfqo
spring.datasource.username=root
spring.datasource.password=TN1FFAxtntIVs2jtbgL53SqKah98Iir2
spring.datasource.driver-class-name=org.postgresql.Driver

# Redis
spring.redis.url=redis://red-d6rctb7afjfc73f50h40:6379

# Base URL
app.base-url=https://url-shortener-9opq.onrender.com

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect